apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: 101.101.0.133:5000/service-b:latest
          ports:
            - containerPort: 8081
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector.monitoring.svc.cluster.local:4317"
            - name: DATABASE_URL
              value: "postgres://user:password@postgres.default.svc.cluster.local:5432/dbname"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
